BeHonest/BeHonest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("news/", include("news.urls")),
    path("", include("main.urls")),
    path("home/", include("post.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BeHonest/blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'
urlpatterns = [
    path('', views.PostList.as_view(), name='base'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

BeHonest/main/urls.py
from django.urls import path
from . import views
from post.views import post_list

app_name = "main"

# slashes after login and register are needed
urlpatterns = [
    path("home", post_list, name="base"),
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("", views.homepage, name="homepage"),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
    # Forget Password urls
    path("password_reset", views.password_reset_request, name="password_reset"),
    path(
        "reset/<uidb64>/<token>",
        views.passwordResetConfirm,
        name="password_reset_confirm",
    ),
    path("send_friend_request", views.AddFriend, name="add_friend"),
    path("accept_friend_request", views.AcceptFriend, name="accept_friend"),
    path("delete_friend", views.DeleteFriend, name="delete_friend"),
]

BeHonest/news/urls.py
from . import views
from django.urls import path

app_name = "news"
urlpatterns = [
    path("", views.index),
]

BeHonest/post/urls.py
from . import views
from django.urls import path

app_name = "post"
urlpatterns = [
    path("", views.post_list, name="base"),
    path("<int:id>/", views.post_detail, name="post_detail"),
    path("news/<int:id>/", views.news_detail, name="news_detail"),
    # path("logout/", views.logout_request, name="logout"),
    path("like/<int:pk>", views.like_post, name="like_post"),
    path("profile/<str:pk>", views.profile, name="profile"),
    path("dislike/<int:pk>", views.dislike_post, name="dislike_post"),
    path("react/<int:pk>", views.react_post, name="react_post"),
    path("delete/<int:pk>", views.delete_post, name="delete_post"),
    path("delete_user/<str:pk>/", views.delete_user, name="delete_user"),
    path("search_results", views.search_results, name="search-results"),
    path("prof_results", views.prof_results, name="prof-results"),
    path("edit/<int:pk>", views.post_update, name="post_update"),
]

BeHonest/news/models.py
from django.db import models
from django.contrib.auth.models import User


class News(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    desc = models.CharField(max_length=10, blank=True, null=True)
    img = models.CharField(max_length=4000, blank=True, null=True)
    url = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.title


class newsComment(models.Model):
    post = models.ForeignKey(News, on_delete=models.CASCADE, related_name="newscomment")
    author = models.ForeignKey(
        User, default=User.objects.first().id, on_delete=models.CASCADE
    )
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return "Comment {} by {}".format(self.content, self.author)

BeHonest/post/forms.py
from .models import Comment, Post
from django import forms
from news.models import newsComment
from profanity import profanity


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

    def clean(self):

        # data from the form is fetched using super function
        super(CommentForm, self).clean()

        # extract the username and text field from the data
        content = self.cleaned_data.get("content")

        # conditions to be met for the username length
        # if profanity.contains_profanity(content):
        if profanity.contains_profanity(content):
            self._errors["content"] = self.error_class(["please be polite"])

        # return any errors if found
        return self.cleaned_data


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "content")

    def clean(self):

        # data from the form is fetched using super function
        super(PostForm, self).clean()

        # extract the username and text field from the data
        title = self.cleaned_data.get("title")
        content = self.cleaned_data.get("content")

        if (isinstance(title, str)):
            # conditions to be met for the username length
            if profanity.contains_profanity(title):
                self._errors["title"] = self.error_class(["please be polite"])
            if profanity.contains_profanity(content):
                self._errors["content"] = self.error_class(["please be polite"])
            #if profanity.contains_profanity(title):
            #     self._errors["title"] = self.error_class(["please be polite"])
            # if profanity.contains_profanity(content):
            #     self._errors["content"] = self.error_class(["please be polite"])

            # return any errors if found
            return self.cleaned_data

class NewsForm(forms.ModelForm):
    class Meta:
        model = newsComment
        fields = ("content",)

    def clean(self):

        # data from the form is fetched using super function
        super(NewsForm, self).clean()

        # extract the username and text field from the data
        content = self.cleaned_data.get("content")

        # conditions to be met for the username length
        # if profanity.contains_profanity(content):
        #     self._errors["content"] = self.error_class(["please be polite"])
        if profanity.contains_profanity(content):
            self._errors["content"] = self.error_class(["please be polite"])
            # return any errors if found
        return self.cleaned_data

BeHonest/news/views.py
from django.shortcuts import render
from newsapi import NewsApiClient
from .models import News


# Create your views here.


def index(request):
    api = NewsApiClient(api_key="084b04d11f594e6a90cb0e4f8b0fab81")
    crypto_news = api.get_everything(q="NYC weather")
    a = crypto_news["articles"]
    title = []
    img = []
    url = []
    for i in range(len(a)):
        f = a[i]
        desc = f["description"]
        if News.objects.filter(desc=desc).exists():
            continue
        else:
            news_data = News(
                title=f["title"],
                desc=f["description"],
                img=f["urlToImage"],
                url=f["url"],
            )
            title.append(f["title"])

            img.append(f["urlToImage"])
            url.append(f["url"])
            news_data.save()

    new_post = None
    # Comment posted
    refresh_queryset = News.objects.order_by("desc")
    return render(
        request,
        "new.html",
        {
            "post_list": refresh_queryset,
            "post": refresh_queryset,
            "new_comment": new_post,
        },
    )
    #
    # mylist = zip(title, desc, img, url)
    #
    # context = {"mylist": mylist}
    #
    # return render(request, "new.html", context)

BeHonest/post/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import CommentForm, PostForm, NewsForm
from news.models import News
from post.models import Post
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from .badges import total_likes_received
from .badges import total_dislikes_received
from .badges import user_likes_badges_tier
from .badges import user_dislikes_badges_tier
from .badges import user_friends_tier
from .badges import post_tier
from .badges import balance_badge
from random import shuffle
from main.models import FriendRequest, Friend
from .user_statistics import most_liked_post, most_disliked_post
from datetime import datetime, timedelta
import pytz

sorts = ["Like", "Date", "Hot"]
utc = pytz.UTC


@login_required(login_url="/")  # redirect when user is not logged in
def search_results(request):
    if request.method == "POST":
        if request.user is not None:
            user = get_object_or_404(User, username=str(request.user))

            try:

                friends_list = Friend.objects.filter(primary=user)

            except Friend.DoesNotExist:

                friends_list = []

            usernames = []
            for i in range(0, len(friends_list)):
                usernames.append(friends_list[i].secondary)
            searched = request.POST.get("searched")
            posts = Post.objects.filter(title__contains=searched)
            posts = posts.filter(author__in=usernames) | posts.filter(author=user)
            return render(
                request, "search_results.html", {"searched": searched, "posts": posts}
            )
    else:
        return render(request, "search_results.html", {})


@login_required(login_url="/")  # redirect when user is not logged in
def prof_results(request):
    if request.method == "POST":
        searched = request.POST.get("searched")
        profs = User.objects.filter(username__contains=searched)
        return render(
            request, "prof_results.html", {"searched": searched, "profs": profs}
        )
    else:
        return render(request, "prof_results.html", {})


def like_post(request, pk):
    post = get_object_or_404(Post, id=request.POST.get("post_id"))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    elif post.dislikes.filter(id=request.user.id).exists():
        post.dislikes.remove(request.user)
        post.likes.add(request.user)
    else:
        post.likes.add(request.user)
    return HttpResponseRedirect(reverse("post:post_detail", args=[str(pk)]))


def dislike_post(request, pk):

    post = get_object_or_404(Post, id=request.POST.get("post_id"))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        post.dislikes.add(request.user)
    elif post.dislikes.filter(id=request.user.id).exists():
        post.dislikes.remove(request.user)
    else:
        post.dislikes.add(request.user)
    return HttpResponseRedirect(reverse("post:post_detail", args=[str(pk)]))


def react_post(request, pk):

    post = get_object_or_404(Post, id=request.POST.get("post_id"))

    if request.POST["function"] == "subtract":
        if request.POST["react_type"] == "beginner":

            post.beginner_react.remove(request.user)
        elif request.POST["react_type"] == "medium":

            post.medium_react.remove(request.user)
        elif request.POST["react_type"] == "expert":

            post.expert_react.remove(request.user)
        elif request.POST["react_type"] == "legend":

            post.legend_react.remove(request.user)
    elif request.POST["function"] == "add":

        if request.POST["react_type"] == "beginner":

            post.beginner_react.add(request.user)
        elif request.POST["react_type"] == "medium":

            post.medium_react.add(request.user)
        elif request.POST["react_type"] == "expert":

            post.expert_react.add(request.user)
        elif request.POST["react_type"] == "legend":

            post.legend_react.add(request.user)

    return HttpResponseRedirect(reverse("post:post_detail", args=[str(pk)]))


@login_required(login_url="/")  # redirect when user is not logged in
def delete_post(request, pk):
    post = get_object_or_404(Post, id=request.POST.get("post_id"))
    # security check so only current user can delete posts
    if request.user == post.author:
        post.delete()
        return HttpResponseRedirect(reverse("post:base"))


@login_required(login_url="/")  # redirect when user is not logged in
def delete_user(request, pk):
    u = get_object_or_404(User, username=request.POST.get("username"))
    if request.user.username == u.username:
        u.delete()
        messages.success(request, "The user is deleted")
        return HttpResponseRedirect(reverse("main:homepage"))
    # try:
    #     u = get_object_or_404(User, username=request.POST.get("username"))
    #     u.delete()
    #     messages.success(request, "The user is deleted")
    #     HttpResponseRedirect(reverse("main:homepage"))
    # except User.DoesNotExist:
    #     messages.error(request, "User does not exist")
    #     redirect_str = "/home/profile/" +str(request.user)
    #     return redirect(redirect_str)
    # except Exception as e:
    #     messages.error(request, {'err':e.message})
    #     redirect_str = "/home/profile/" +str(request.user)
    #     return redirect(redirect_str)


@login_required(login_url="/")  # redirect when user is not logged in
def post_list(request):
    s = request.POST.get("sorts")
    if request.user is not None:
        user = get_object_or_404(User, username=str(request.user))

        try:

            friends_list = Friend.objects.filter(primary=user)

        except Friend.DoesNotExist:

            friends_list = []

        usernames = []
        for i in range(0, len(friends_list)):
            usernames.append(friends_list[i].secondary)

        if request.method == "POST":
            if "link" in request.POST:
                post_form = PostForm()
                new_post = None
                new_post = post_form.save(False)
                auto_populate = request.POST["link"]
                if s == "Like":
                    refresh_queryset = Post.objects.annotate(
                        count=Count("likes")
                    ).order_by("-count")
                elif s == "Hot":
                    now = datetime.now()
                    now = utc.localize(now)
                    refresh_queryset = (
                        Post.objects.filter(
                            created_on__date__gte=now - timedelta(hours=4)
                        )
                        .annotate(count=Count("likes"))
                        .order_by("-count")
                    )
                else:
                    refresh_queryset = Post.objects.order_by("-created_on")
                refresh_queryset = refresh_queryset.filter(
                    author__in=usernames
                ) | refresh_queryset.filter(author=user)

                return render(
                    request,
                    "index.html",
                    {
                        "post_list": refresh_queryset,
                        "post": refresh_queryset,
                        "new_comment": new_post,
                        "comment_form": post_form,
                        "auto_populate": auto_populate,
                    },
                )

        new_post = None
        # Comment posted
        if request.method == "POST":
            post_form = PostForm(data=request.POST)
            if post_form.is_valid():
                # Create Comment object but don't save to database yet
                new_post = post_form.save(False)
                new_post.author = request.user
                # Save the comment to the database
                new_post.save()
        else:
            post_form = PostForm()

        if s == "Like":
            refresh_queryset = Post.objects.annotate(count=Count("likes")).order_by(
                "-count"
            )
        elif s == "Hot":
            now = datetime.now()
            now = utc.localize(now)
            refresh_queryset = (
                Post.objects.filter(created_on__date__gte=now - timedelta(hours=6))
                .annotate(count=Count("likes"))
                .order_by("-count")
            )
            # r2 = Post.objects.filter(
            # created_on__date__lt = now - timedelta(hours=4)).annotate(count=Count("likes")).order_by("-count")
            # refresh_queryset = r1 | r2
        else:
            refresh_queryset = Post.objects.order_by("-created_on")
        refresh_queryset = refresh_queryset.filter(
            author__in=usernames
        ) | refresh_queryset.filter(author=user)

        return render(
            request,
            "index.html",
            {
                "post_list": refresh_queryset,
                "post": refresh_queryset,
                "new_comment": new_post,
                "comment_form": post_form,
                "sorts": sorts,
            },
        )


@login_required(login_url="/")
def post_update(request, pk):

    if request.method == "GET":

        post = get_object_or_404(Post, id=pk)
        template_name = "post_update.html"
        if request.user == post.author:

            return render(
                request,
                template_name,
                {
                    "post": post,
                    "title": post.title,
                    "content": post.content,
                },
            )

    else:

        template_name = "post_detail.html"

        post = Post.objects.get(id=int(request.POST["pk"]))

        if request.user == post.author:

            post.title = request.POST["title"]

BeHonest/post/templates/base-backup.html
<!DOCTYPE html>
<html>
  <head>
    <title> Behonest</title>

    <link
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
      rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

  </head>

  <body>
    <style>
      body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #fdfdfd;
      }

    .shadow{
           box-shadow: 0 4px 2px -2px rgba(0,0,0,0.1);
       }
      .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
      }

     .masthead {
              background:#3398E1;
              height: auto;
              padding-bottom: 15px;
              box-shadow: 0 16px 48px #E3E7EB;
              padding-top: 10px;
    }
    </style>
     {% if user.is_authenticated %}
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'post:base' %}">Behonest</a>
        <!-- <button
          class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button> -->
        
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

            <li class="nav-item text-black">
              <a
                class="nav-link text-black font-weight-bold"
                href="#"
                >About</a
              >
            </li>
            <li class="nav-item text-black">
              <a
                class="nav-link text-black font-weight-bold"
                href="#"
                >Policy</a
              >
            </li>
            <li class="nav-item text-black">
              <a
                class="nav-link text-black font-weight-bold"
                href="#"
                >Contact</a
              >
            </li>
          </ul>
        </div>


      </div>
    </div>
    </nav>


            {% block content %}
            
          <!-- Content Goes here -->
            {% endblock content %}
            {% else %}
    
            <li class="nav-item">
            <a class="nav-link" href="login">Login</a>
            </li>
    
            {% endif %}
    <!-- Footer -->
    <footer class="py-3 bg-grey">
              <p class="m-0 text-dark text-center ">Copyright &copy; Inet team4</p>
    </footer>

  </body>
</html>

BeHonest/post/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title> Behonest</title>
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
      rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href = {% static 'styles.css' %}>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Carter+One&family=Fredoka+One&family=Oswald&display=swap" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Favicon Configuration -->
    <link rel="icon" type="image/x-icon" href="/static/img/favicon.ico">
    <!-- Favicon configuration not working in development-->

  </head>

  <body>

    {% if user.is_authenticated %}
    <!-- <h1>Working</h1> -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow" id="mainNav">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'post:base' %}">
          <img src="{% static 'img/Febee.png' %}" alt="Febee" class="logo">
          BeHonest
        </a>

        <form class="d-flex" method="POST" action="{% url 'post:search-results' %}" >
          {% csrf_token %}
          <input class="form-control me-2"
          type = "search" placeholder="Search" aria-label="Search" name="searched">
          <button class="btn btn-outline-secondary" type="submit">Search</button>

        </form>
        
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'main:logout' %}">Logout</a>
              </li>
              <li class="nav-item">

                {% if authenticated_user  == Null  %}
                <a class="nav-link text-white" href="/home/profile/{{user.username}}">{{user.username}}</a>
                {% else %}
                <a class="nav-link text-white" href="/home/profile/{{authenticated_user.username}}">{{authenticated_user.username}}</a>
                {% endif %}
              </li>
              <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">

                  {% comment %} <li class="nav-item text-black"> {% endcomment %}
                    <a
                      class="nav-link text-black font-weight-bold"
                      href="/news"
                      >NYC News</a
                    >
                  </li>
                </ul>
              </div>
          </ul>
        </div>
        </div>
      </div>
    </nav>


    {% block content %}
            <!-- Content Goes here -->
    {% endblock content %}
    {% else %}
    <!-- <h1>Working-not</h1> -->
    <!-- <p class="text-center">Don't have an account? <a href="register">Create an account</a>.</p> -->

      <p class="text-center">Don't have an account? <a href="register">Create an account</a>.</p>
    </div>

    {% endif %}
    <!-- Navigation -->


    <!-- Footer -->
    <footer class="py-3 bg-grey">
              <p class="m-0 text-dark text-center ">Copyright &copy; Inet team4</p>
    </footer>

  </body>
</html>

BeHonest/post/templates/index.html
{% extends "base.html" %}

 {% block content %}
<style>

    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text{
    color: white;
  }
    .card{
    box-shadow: 0 16px 48px #E3E7EB;
}
</style>
{% comment %} <header class="masthead" >
  <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class=" col-md-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to Behonest </h3>
            <p class="text-light">anonymous posts ..! &nbsp
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</header> {% endcomment %}
<br>
<center>
<div class="form-group col-md-4">
  <form class="d-flex" method="POST" action="{% url 'post:base'%}" >
    {% csrf_token %}
    <select id="sorts" class="form-control" name="sorts">
      <option selected>Sort By...</option>
      {% for sort in sorts %}
      <option value="{{ sort }}">{{ sort }}</option>
      {% endfor %}
      
    </select>
    <button class="btn btn-primary" type="submit">Sort</button>
  </form>
</div>
<div class="container">
  <div class="row">
    <!-- Blog Entries Column -->
    <div class="col-md-8 mt-3 left">
      {% for post in post_list %}
      {% if post.checknew %}
        <div class="card mb-4" >
          <div class="card-body">
            {% comment %} <h2 class="card-title">{{ post.title }}</h2> {% endcomment %}
            <a href="{% url 'post:post_detail' post.id  %}"> 
              <h2 class="card-title"> {{ post.title }}</h2>
            </a>
            <p class="card-text text-muted h6">{{ post.created_on}} </p>
            <p class="card-text">{{post.content|slice:":200" }}</p>
            {% comment %} <a href="{% url 'post:post_detail' post.id  %}" class="btn btn-primary">Read More &rarr;</a> {% endcomment %}
          </div>
        </div>
      {% endif %} 
      {% endfor %}
    </div>
      {% block sidebar %}
      {% include 'sidebar.html' %}
      {% endblock sidebar %}
    </div>
</div>
{%endblock%}

BeHonest/post/templates/new.html
{% extends "base.html" %}

 {% block content %}
<style>

    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text{
    color: white;
  }
    .card{
    box-shadow: 0 16px 48px #E3E7EB;
}
</style>
{% comment %} <header class="masthead" >
  <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class=" col-md-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to Behonest </h3>
            <p class="text-light">anonymous posts ..! &nbsp
            </p>
          </div>
        </div>
      </div>
 <div class="card mb-4" >
    <div class="card-body">
      <h2 class="card-title">{{ title}}</h2>
      <br>
     <img src="{{ i }}" alt="">

      <p class="card-text">{{desc|slice:":200" }}</p>
      <a href= "{{ urls }}">Read More</a>
      
    </div>
  </div>
</header> {% endcomment %}

<div class="container">
  <div class="row">
    <!-- Blog Entries Column -->
    <div class="col-md-8 mt-3 left">
      {% for post in post_list %}
        <div class="card mb-4" >
          <div class="card-body">
            <h2 class="card-title">{{ post.title }}</h2>
            <img src="{{ post.img }}" style="width:500px;height:500px; alt="" >

            <p class="card-text">{{post.desc|slice:":200" }}</p>

            <a href="{% url 'post:news_detail' post.id  %}" class="btn btn-primary">Read More &rarr;</a>
            
          </div>
        </div>
      {% endfor %}
    </div>

    </div>
</div>
{%endblock%}

BeHonest/post/templates/prof_results.html
{% extends "base.html" %}

 {% block content %}
<style>

    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text{
    color: white;
  }
    .card{
    box-shadow: 0 16px 48px #E3E7EB;
}
</style>
    <center>
        {% if searched %}
            <h1> You Searched For "{{searched }}"</h1>
            <br/>
            <div style="display: flex; margin:0 auto;">
                <form class="d-flex" method="POST" action="{% url 'post:prof-results' %}" style="float:left;">
                    {% csrf_token %}
                    <input type='hidden' name='searched' value= "{{searched}}">  
                    <button class="btn btn-outline-secondary">Profile</button>
          
                  </form>
    
                  <form class="d-flex" method="POST" action="{% url 'post:search-results' %}" style="float:right;">
                    {% csrf_token %}
                    <input type='hidden' name='searched' value= "{{searched}}">  
                    <button class="btn btn-outline-secondary" >Posts</button>
          
                  </form>
            </div>
            <br/>
            <br/>
            {% for prof in profs %}
                <div class="card mb-4" >
                <div class="card-body">
                    <h2 class="card-title">{{ prof.username }}</h2>
                    <a href="/home/profile/{{prof.username}}"  class="btn btn-primary">Profile </a>

                </div>
                </div>

            {% endfor %}

        
        {% else %}
            <h1>Hey! You Forgot to Search</h1>
        
        {% endif %}

    </center>
{%endblock%}

BeHonest/post/templates/search_results.html
{% extends "base.html" %}

 {% block content %}
<style>

    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text{
    color: white;
  }
    .card{
    box-shadow: 0 16px 48px #E3E7EB;
}
</style>
    <center>
        {% if searched %}
            <h1> You Searched For "{{searched }}"</h1>
            <br/>
            <div style="display: flex; margin:0 auto;">
            <form class="d-flex" method="POST" action="{% url 'post:prof-results' %}" style="float:left;">
                {% csrf_token %}
                <input type='hidden' name='searched' value= "{{searched}}">  
                <button class="btn btn-outline-secondary">Profile</button>
      
              </form>

              <form class="d-flex" method="POST" action="{% url 'post:search-results' %}" style="float:right;">
                {% csrf_token %}
                <input type='hidden' name='searched' value= "{{searched}}">  
                <button class="btn btn-outline-secondary" >Posts</button>
      
              </form>
            </div>
            <br/>
            <br/>
            {% for post in posts %}
            {% if post.checknew %}
            <div class="card mb-4" >
            <div class="card-body">
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text text-muted h6">{{ post.created_on}} </p>
                <p class="card-text">{{post.content|slice:":200" }}</p>
                <a href="{% url 'post:post_detail' post.id  %}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            </div>
            {% endif %} 
            {% endfor %}
        
        {% else %}
            <h1>Hey! You Forgot to Search</h1>
        
        {% endif %}

    </center>
{%endblock%}