BeHonest/BeHonest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("news/", include("news.urls")),
    path("", include("main.urls")),
    path("home/", include("post.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BeHonest/blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'
urlpatterns = [
    path('', views.PostList.as_view(), name='base'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

BeHonest/main/urls.py
from django.urls import path
from . import views
from post.views import post_list

app_name = "main"

# slashes after login and register are needed
urlpatterns = [
    path("home", post_list, name="base"),
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("", views.homepage, name="homepage"),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
    # Forget Password urls
    path("password_reset", views.password_reset_request, name="password_reset"),
    path(
        "reset/<uidb64>/<token>",
        views.passwordResetConfirm,
        name="password_reset_confirm",
    ),
    path("send_friend_request", views.AddFriend, name="add_friend"),
    path("accept_friend_request", views.AcceptFriend, name="accept_friend"),
    path("delete_friend", views.DeleteFriend, name="delete_friend"),
]

BeHonest/post/urls.py
from . import views
from django.urls import path

app_name = "post"
urlpatterns = [
    path("", views.post_list, name="base"),
    path("<int:id>/", views.post_detail, name="post_detail"),
    path("news/<int:id>/", views.news_detail, name="news_detail"),
    # path("logout/", views.logout_request, name="logout"),
    path("like/<int:pk>", views.like_post, name="like_post"),
    path("profile/<str:pk>", views.profile, name="profile"),
    path("dislike/<int:pk>", views.dislike_post, name="dislike_post"),
    path("react/<int:pk>", views.react_post, name="react_post"),
    path("delete/<int:pk>", views.delete_post, name="delete_post"),
    path("delete_user/<str:pk>/", views.delete_user, name="delete_user"),
    path("search_results", views.search_results, name="search-results"),
    path("prof_results", views.prof_results, name="prof-results"),
    path("edit/<int:pk>", views.post_update, name="post_update"),
]

BeHonest/main/models.py
# Create your models here.

from django.db import models
from django.contrib.auth.models import User


class FriendRequest(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="receiver"
    )
    created_on = models.DateTimeField(auto_now_add=True)

    status = models.TextField()


class Friend(models.Model):
    primary = models.ForeignKey(User, on_delete=models.CASCADE, related_name="primary")
    secondary = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="secondary"
    )
    created_on = models.DateTimeField(auto_now_add=True)

BeHonest/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.forms import PasswordResetForm
from .models import FriendRequest, Friend

# Create your forms here.


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


# Form to accept New Password
class SetPasswordForm(SetPasswordForm):
    class Meta:
        model = User
        fields = ["new_password1", "new_password2"]


class PasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)

    # captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())


class FriendRequestForm(forms.ModelForm):
    class Meta:
        model = FriendRequest
        fields = (
            "sender",
            "receiver",
            "status",
        )


class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ("primary", "secondary")

BeHonest/main/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage

from .tokens import account_activation_token
from .forms import PasswordResetForm
from .forms import SetPasswordForm
from django.db.models.query_utils import Q
from .forms import FriendRequestForm, FriendForm
from .models import FriendRequest, Friend

# Function added to the url for Email confirmation


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except User.DoesNotExist:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(
            request,
            "Thank you for your email confirmation. Now you can login your account.",
        )
        return redirect("main:login")
    else:
        messages.error(request, "Activation link is invalid!")

    return redirect("main:homepage")


# Function that sends the email
def activateEmail(request, user, to_email):
    mail_subject = "Activate your user account."
    message = render_to_string(
        "template_activate_account.html",
        {
            "user": user.username,
            "domain": get_current_site(request).domain,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": account_activation_token.make_token(user),
            "protocol": "https" if request.is_secure() else "http",
        },
    )
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(
            request,
            f"Dear {user}, please go to you email {to_email} inbox and click on \
            received activation link to confirm and complete the registration. Note: Check your spam folder.",
        )
    else:
        message.error(
            request,
            f"Problem sending email to {to_email}, check if you typed it correctly.",
        )


# Main views


def homepage(request):
    # now if you're already authenticated you can't access base path
    if request.user.is_authenticated:
        return redirect("post:base")
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # messages.info(request, f"You are now logged in as {username}.")
                # return redirect("main:homepage")
                return redirect("post:base")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(
        request=request, template_name="main/home.html", context={"login_form": form}
    )


def register_request(request):
    if request.user.is_authenticated:
        return redirect("post:base")
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get("email"))
            # return redirect("main:homepage")
            return redirect("main:login")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(
        request=request,
        template_name="main/register.html",
        context={"register_form": form},
    )


def login_request(request):
    if request.user.is_authenticated:
        return redirect("post:base")
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                # return redirect("main:homepage")
                return redirect("post:base")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(
        request=request, template_name="main/login.html", context={"login_form": form}
    )


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("main:homepage")


# def password_reset_request(request):
#     form = PasswordResetForm()
#     return render(
#         request=request,
#         template_name="password_reset.html",
#         context={"form": form}
#         )

# def passwordResetConfirm(request, uidb64, token):
#     return redirect("main:homepage")


def password_reset_request(request):
    if request.method == "POST":
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            user_email = form.cleaned_data["email"]
            associated_user = (
                get_user_model().objects.filter(Q(email=user_email)).first()
            )
            if associated_user:
                subject = "Password Reset request"
                message = render_to_string(
                    "template_reset_password.html",
                    {
                        "user": associated_user,
                        "domain": get_current_site(request).domain,
                        "uid": urlsafe_base64_encode(force_bytes(associated_user.pk)),
                        "token": account_activation_token.make_token(associated_user),
                        "protocol": "https" if request.is_secure() else "http",
                    },
                )
                email = EmailMessage(subject, message, to=[associated_user.email])
                if email.send():
                    messages.success(request, "Password reset email sent.")
                else:
                    messages.error(
                        request,
                        "Problem sending reset password email, <b>SERVER PROBLEM</b>",
                    )

            return redirect("main:homepage")

        # for key, error in list(form.errors.items()):
        #     if key == 'captcha' and error[0] == 'This field is required.':
        #         messages.error(request, "You must pass the reCAPTCHA test")
        #         continue

    form = PasswordResetForm()
    return render(
        request=request, template_name="password_reset.html", context={"form": form}
    )


def passwordResetConfirm(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except User.DoesNotExist:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        if request.method == "POST":
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(
                    request,
                    "Your password has been set. You may go ahead and <b>log in </b> now.",
                )
                return redirect("main:homepage")
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)

        form = SetPasswordForm(user)
        return render(request, "password_reset_confirm.html", {"form": form})
    else:
        messages.error(request, "Link is expired")

    messages.error(request, "Something went wrong, redirecting back to Homepage")
    return redirect("main:homepage")


def AddFriend(request):
    print("receiver")
    print(request.POST["receiver"])
    print("user")
    print(request.user)
    User = get_user_model()
    sender = User.objects.get(username=request.user)
    receiver = User.objects.get(username=request.POST["receiver"])
    friend_request_form = FriendRequestForm()
    new_friend_request = friend_request_form.save(False)
    new_friend_request.sender = sender
    new_friend_request.receiver = receiver
    new_friend_request.status = "pending"
    new_friend_request.save(True)
    redirect_str = "/home/profile/" + request.POST["receiver"]
    return redirect(redirect_str)


def DeleteFriend(request):
    User = get_user_model()
    deleted_friend = User.objects.get(username=request.POST["friend"])
    deleter = User.objects.get(username=request.user)
    FriendRequest.objects.filter(sender=deleted_friend, receiver=deleter).delete()
    FriendRequest.objects.filter(sender=deleter, receiver=deleted_friend).delete()
    Friend.objects.filter(primary=deleter, secondary=deleted_friend).delete()
    Friend.objects.filter(primary=deleted_friend, secondary=deleter).delete()
    return redirect(request.META.get("HTTP_REFERER"))


def AcceptFriend(request):
    print(request.POST["sender"])
    print(request.user)
    User = get_user_model()
    receiver = User.objects.get(username=request.user)
    sender = User.objects.get(username=request.POST["sender"])

BeHonest/main/templates/main/header.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BeHonest</title>
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href = {% static 'styles.css' %}>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Carter+One&family=Fredoka+One&family=Oswald&display=swap" rel="stylesheet">
  </head>
 <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow" id="mainNav">
    <div class="container-fluid">
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'post:base' %}">
        <img src="{% static 'img/Febee.png' %}" alt="Febee" class="logo">
        BeHonest
      </a>
      {% else %}
      <a class="navbar-brand" href="{% url 'main:homepage' %}">
        <img src="{% static 'img/Febee.png' %}" alt="Febee" class="logo">
        BeHonest
      </a>
      {% endif %}
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-white" href="logout">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="home">{{user.username}}</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link text-white" href= "/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href= "/register">Sign-Up</a>
            </li>
          {% endif %}
        </ul>
      </div>
      </div>
    </div>
  </nav>
  {% include 'main/includes/messages.html' %}
  

  {% block content %}

  {% endblock %}

  <!-- Optional Javascript -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

BeHonest/main/templates/main/login.html
{% extends "main/header.html" %}

{% block content %}      

{% load crispy_forms_tags %}

<!-- Login -->
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <!-- Forget Password link -->
  <a href="{% url 'main:password_reset' %}">Forgot password?</a>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>

{% endblock %}

BeHonest/main/templates/main/register.html
{% extends "main/header.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!-- Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<h3>check</h3>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
		
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>



{% endblock %}